' @file      YoutubeAutoComment_ScequenceDiagram_v01.pu
' @brief     高度情報演習2B プロジェクト計画書のシーケンス図の出力用ファイル
' @note      java -jar plantuml.jar -graphvizdot C:\Graphviz\bin\dot.exe -charset UTF-8 .\YoutubeAutoComment_ScequenceDiagram.pu
' @auther    AL18036 Kataoka Nagi
' @date      2020-12-16 10:23:46
' $Version   1.0
' $Revision  1.0
' @par       変更点：全体の草案の新規作成
' @see       https://qiita.com/opengl-8080/items/98c510b8ca060bdd2ea3

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

@startuml out/ScequenceDiagram.png
scale 1.5
skinparam DefaultFontName メイリオ
' 可視性の変更
skinparam classAttributeIconSize 0

''''''''''''''''''''''''''''''''''''''''''''''''''

title
**1分ごとに起動する本システムの全体像**
end title

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

actor User
participant YoutubeAutoComment.java
participant API.java
participant JSONHttpRequest.java
participant Config.java
' 冗長？
' participant HashMap.java
' participant ObjectMapper.java

' participant EmoationAnalyser.java
' participant ReplyGenerator.java

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
activate YoutubeAutoComment.java

activate User
User -> User: Comment on Youtube
deactivate User

''''''''''''''''''''''''''''''''''''''''''''''''''
' activate YoutubeAutoComment.java
YoutubeAutoComment.java -> YoutubeAutoComment.java: Every 1 min.
' deactivate YoutubeAutoComment.java

''''''''''''''''''''''''''''''''''''''''''''''''''

YoutubeAutoComment.java -> API.java: commentThreadList(videoId: String)\n: CommentThreadListResponse
activate API.java

''''''''''''''''''''''''''''''''''''''''''''''''''

API.java -> Config.java: getHttpProxyEnabled(): boolean
activate Config.java
deactivate Config.java

alt getHttpProxyEnabled() == true
  API.java -> JSONHttpRequest.java: JSONHttpRequest(proxy: Proxy, method: String, baseUrl: String)
  activate JSONHttpRequest.java
else else
  API.java -> JSONHttpRequest.java: JSONHttpRequest(method: String, baseUrl: String)
end

''''''''''''''''''''''''''''''''''''''''''''''''''

API.java -> Config.java: getApiKey(): String
activate Config.java
deactivate Config.java

' 冗長？
' API.java -> HashMap.java: put(K: Object, V: Object)
' API.java -> HashMap.java
' API.java -> HashMap.java
' API.java -> HashMap.java
' API.java -> HashMap.java

''''''''''''''''''''''''''''''''''''''''''''''''''

API.java -> JSONHttpRequest.java: setParams(params: Map<String, String>)\n: JSONHttpRequest
API.java -> JSONHttpRequest.java: doRequest(): JSONHttpRequest
API.java -> JSONHttpRequest.java: getResponse(): String

''''''''''''''''''''''''''''''''''''''''''''''''''

@enduml
