' @file      YoutubeAutoComment_SequenceDiagram_CommentAnalyser.pu
' @brief     高度情報演習2B プロジェクト計画書のシーケンス図の出力用ファイル（コメント解析パート）
' @note      java -jar plantuml.jar -graphvizdot C:\Graphviz\bin\dot.exe -charset UTF-8 .\*.pu
' @auther    AL18036 Kataoka Nagi
' @date      2021-01-05 06:05:48
' $Version   1.2
' $Revision  1.0
' @par       修正点：commentsInsert()の引数
' @see       https://qiita.com/opengl-8080/items/98c510b8ca060bdd2ea3

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

@startuml out/SequenceDiagram_CommentAnalyser.png
scale 1.5
skinparam DefaultFontName メイリオ
' 可視性の変更
skinparam classAttributeIconSize 0

''''''''''''''''''''''''''''''''''''''''''''''''''

title
**Youtubeコメントの解析 / 返信**
end title

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

actor User
participant YoutubeAutoComment.java
participant ReplyGenerator.java
participant EmotionAnalyser.java
participant AOuthHelper.java
participant MeCab
participant PolarDictionary
participant Timer.java
participant API.java

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
activate YoutubeAutoComment.java
YoutubeAutoComment.java -> ReplyGenerator.java: ReplyGenerator()
activate ReplyGenerator.java

''''''''''''''''''''''''''''''''''''''''''''''''''

ReplyGenerator.java -> EmotionAnalyser.java: EmotionAnalyser()
activate EmotionAnalyser.java

''''''''''''''''''''''''''''''''''''''''''''''''''

EmotionAnalyser.java -> MeCab: getCommentSurfaceList(): List<String> 
' EmotionAnalyser.java -> MeCab: exec(String: mecabCommand): Process
activate MeCab
deactivate MeCab

''''''''''''''''''''''''''''''''''''''''''''''''''

EmotionAnalyser.java -> PolarDictionary: positiveLevelMap.put\n(String: wordPolarInfo[0].trim(), int: wordPositiveLevel)
activate PolarDictionary
deactivate PolarDictionary

''''''''''''''''''''''''''''''''''''''''''''''''''

YoutubeAutoComment.java -> Timer.java: Timer()
activate Timer.java

''''''''''''''''''''''''''''''''''''''''''''''''''

YoutubeAutoComment.java -> ReplyGenerator.java: generate(comment: String,\n positiveLevel: double): String

''''''''''''''''''''''''''''''''''''''''''''''''''

ReplyGenerator.java -> EmotionAnalyser.java: getPositiveLevel(comment: String): double
EmotionAnalyser.java -> EmotionAnalyser.java: evalFunc(positiveCnt: int,\n negativeCnt: int): double


''''''''''''''''''''''''''''''''''''''''''''''''''

' YoutubeAutoComment.java -> AOuthHelper.java: authorize()\nアプリ管理者が、任意のタイミングでブラウザからYoutubeの権限を認証

''''''''''''''''''''''''''''''''''''''''''''''''''

YoutubeAutoComment.java -> API.java:  commentsInsert(credential: Credential, parentId: String, commentText: String): Comment
activate API.java
deactivate API.java

''''''''''''''''''''''''''''''''''''''''''''''''''

YoutubeAutoComment.java -> Timer.java: scheduleAtFixedRate(Runnable command, long initialDelay, long period)

''''''''''''''''''''''''''''''''''''''''''''''''''

activate User
User -> User: Read comment on Youtube
deactivate User

@enduml
